### ISSUE TITLE
Add View on Query Param

### ISSUE THREAD

**Issue by kbtonmoy** [eugenezadorin/airtable-php#6]
It seems like there is no option to add a view name on the query. 
Something like 
`$query = $client->table($able)->view("my view")->execute()` 
would be very handy.

**Comment by eugenezadorin** [comment]
Hi! Thanks for feedback.

You're right, the library currently doesn't know how to work with views.

I like your approach, it looks clean and pretty easy to implement on the first glance... But I need some research here.

Please, stay tuned!

**Comment by kbtonmoy** [comment]
You have done a great job man. I wish to see this feature soon. I use this library almost every day.

**Comment by eugenezadorin** [comment]
Implemented in v0.6.0

Please check out documentation - https://github.com/eugenezadorin/airtable-php#view
