### ISSUE TITLE
Set $this->handler in Request within the construct

### ISSUE THREAD

**Issue by logistiker** [eugenezadorin/airtable-php#7]
It would be helpful if you set $this->handler to initialize curl within the construct instead of within the send method so that the entire send method does not have to be replaced just to use different curl options.

**Comment by eugenezadorin** [comment]
Hi! Thanks for your feedback.

Can you please provide more information about the issue you want to solve?

As I can see, `$this->handler` actually can just be replaced with local variable, there is no need to keep it as class property at all. 

CURL options are related to Airtable API server, is there any reason to change/override them from outside? If so, I probably can extract CURL configuration to small protected method, which can be easily overridden.

**Comment by logistiker** [comment]
The request class doesn't have to be used for airtable only.  You can use it for other things since it's not airtable specific.  So if you want to use it for something other than airtable and on a server with a self-signed certificate, you have to override the whole function to change the curl configuration which negates the entire method.

**Comment by eugenezadorin** [comment]
No, actually Request class **is** airtable-specific and should be used only inside this library.

If you need general purpose class, it will probably better to use something like [guzzle](https://github.com/guzzle/guzzle)
